// Generated by gencpp from file move_zumy/Mov2LocSrvResponse.msg
// DO NOT EDIT!


#ifndef MOVE_ZUMY_MESSAGE_MOV2LOCSRVRESPONSE_H
#define MOVE_ZUMY_MESSAGE_MOV2LOCSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_zumy
{
template <class ContainerAllocator>
struct Mov2LocSrvResponse_
{
  typedef Mov2LocSrvResponse_<ContainerAllocator> Type;

  Mov2LocSrvResponse_()
    : isPosReached(false)  {
    }
  Mov2LocSrvResponse_(const ContainerAllocator& _alloc)
    : isPosReached(false)  {
    }



   typedef uint8_t _isPosReached_type;
  _isPosReached_type isPosReached;




  typedef boost::shared_ptr< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Mov2LocSrvResponse_

typedef ::move_zumy::Mov2LocSrvResponse_<std::allocator<void> > Mov2LocSrvResponse;

typedef boost::shared_ptr< ::move_zumy::Mov2LocSrvResponse > Mov2LocSrvResponsePtr;
typedef boost::shared_ptr< ::move_zumy::Mov2LocSrvResponse const> Mov2LocSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_zumy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82edab1b5e93c62971c68966b7a3c845";
  }

  static const char* value(const ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82edab1b5e93c629ULL;
  static const uint64_t static_value2 = 0x71c68966b7a3c845ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_zumy/Mov2LocSrvResponse";
  }

  static const char* value(const ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isPosReached\n\
";
  }

  static const char* value(const ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isPosReached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Mov2LocSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_zumy::Mov2LocSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "isPosReached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isPosReached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ZUMY_MESSAGE_MOV2LOCSRVRESPONSE_H
