// Generated by gencpp from file move_zumy/Mov2LocSrv.msg
// DO NOT EDIT!


#ifndef MOVE_ZUMY_MESSAGE_MOV2LOCSRV_H
#define MOVE_ZUMY_MESSAGE_MOV2LOCSRV_H

#include <ros/service_traits.h>


#include <move_zumy/Mov2LocSrvRequest.h>
#include <move_zumy/Mov2LocSrvResponse.h>


namespace move_zumy
{

struct Mov2LocSrv
{

typedef Mov2LocSrvRequest Request;
typedef Mov2LocSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Mov2LocSrv
} // namespace move_zumy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_zumy::Mov2LocSrv > {
  static const char* value()
  {
    return "486d05b8548358882df27b5102476843";
  }

  static const char* value(const ::move_zumy::Mov2LocSrv&) { return value(); }
};

template<>
struct DataType< ::move_zumy::Mov2LocSrv > {
  static const char* value()
  {
    return "move_zumy/Mov2LocSrv";
  }

  static const char* value(const ::move_zumy::Mov2LocSrv&) { return value(); }
};


// service_traits::MD5Sum< ::move_zumy::Mov2LocSrvRequest> should match 
// service_traits::MD5Sum< ::move_zumy::Mov2LocSrv > 
template<>
struct MD5Sum< ::move_zumy::Mov2LocSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_zumy::Mov2LocSrv >::value();
  }
  static const char* value(const ::move_zumy::Mov2LocSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_zumy::Mov2LocSrvRequest> should match 
// service_traits::DataType< ::move_zumy::Mov2LocSrv > 
template<>
struct DataType< ::move_zumy::Mov2LocSrvRequest>
{
  static const char* value()
  {
    return DataType< ::move_zumy::Mov2LocSrv >::value();
  }
  static const char* value(const ::move_zumy::Mov2LocSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_zumy::Mov2LocSrvResponse> should match 
// service_traits::MD5Sum< ::move_zumy::Mov2LocSrv > 
template<>
struct MD5Sum< ::move_zumy::Mov2LocSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_zumy::Mov2LocSrv >::value();
  }
  static const char* value(const ::move_zumy::Mov2LocSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_zumy::Mov2LocSrvResponse> should match 
// service_traits::DataType< ::move_zumy::Mov2LocSrv > 
template<>
struct DataType< ::move_zumy::Mov2LocSrvResponse>
{
  static const char* value()
  {
    return DataType< ::move_zumy::Mov2LocSrv >::value();
  }
  static const char* value(const ::move_zumy::Mov2LocSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_ZUMY_MESSAGE_MOV2LOCSRV_H
