# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ar_coord/ZumyCoord.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import genpy
import std_msgs.msg

class ZumyCoord(genpy.Message):
  _md5sum = "100d2833b93ecf2b5920ca100a6fdaf8"
  _type = "ar_coord/ZumyCoord"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string zumyID
std_msgs/Time time
geometry_msgs/Pose2D position


================================================================================
MSG: std_msgs/Time
time data

================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
"""
  __slots__ = ['zumyID','time','position']
  _slot_types = ['string','std_msgs/Time','geometry_msgs/Pose2D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       zumyID,time,position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ZumyCoord, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.zumyID is None:
        self.zumyID = ''
      if self.time is None:
        self.time = std_msgs.msg.Time()
      if self.position is None:
        self.position = geometry_msgs.msg.Pose2D()
    else:
      self.zumyID = ''
      self.time = std_msgs.msg.Time()
      self.position = geometry_msgs.msg.Pose2D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.zumyID
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I3d.pack(_x.time.data.secs, _x.time.data.nsecs, _x.position.x, _x.position.y, _x.position.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.time is None:
        self.time = std_msgs.msg.Time()
      if self.position is None:
        self.position = geometry_msgs.msg.Pose2D()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.zumyID = str[start:end].decode('utf-8')
      else:
        self.zumyID = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.time.data.secs, _x.time.data.nsecs, _x.position.x, _x.position.y, _x.position.theta,) = _struct_2I3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.zumyID
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I3d.pack(_x.time.data.secs, _x.time.data.nsecs, _x.position.x, _x.position.y, _x.position.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.time is None:
        self.time = std_msgs.msg.Time()
      if self.position is None:
        self.position = geometry_msgs.msg.Pose2D()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.zumyID = str[start:end].decode('utf-8')
      else:
        self.zumyID = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.time.data.secs, _x.time.data.nsecs, _x.position.x, _x.position.y, _x.position.theta,) = _struct_2I3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2I3d = struct.Struct("<2I3d")
